import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { MuiThemeProvider } from "@/providers/MuiThemeProvider";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  style: "normal",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
  adjustFontFallback: true
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${raleway.variable}`}>
        <MuiThemeProvider>{children}</MuiThemeProvider>
      </body>
    </html>
  );
}
